# Generated by Django 3.0.8 on 2020-07-31 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fligh',
            new_name='Flight',
        ),
    ]
