# Generated by Django 3.0.8 on 2020-07-31 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='las',
            new_name='last',
        ),
    ]
