# Generated by Django 3.0.8 on 2020-07-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
